import { examGuides, levels, resources, textbooks, type CefrLevel, type ResourceCategory } from '@/data';
import type { CatalogFilters, CatalogType } from './catalog-filters';

export type SearchResult = { id: string; type: CatalogType; title: string; description: string; href: string; cefrLevels: CefrLevel[]; tags: string[]; category?: ResourceCategory; access: 'free' | 'paid' | 'mixed'; searchTerms: string[] };
const normalize = (value: string) => value.trim().toLocaleLowerCase('ru-RU');
const terms = (value: string) => normalize(value).split(/\s+/).filter(Boolean);

export const searchIndex: SearchResult[] = [
  ...levels.map((level) => ({ id: level.id, type: 'level' as const, title: `${level.title}: ${level.fullName}`, description: level.description, href: `/plans/${level.slug}`, cefrLevels: level.cefrLevels, tags: level.tags, access: level.access, searchTerms: [level.title, level.fullName, ...level.tags, ...level.cefrLevels] })),
  ...levels.flatMap((level) => [...level.grammar, ...level.vocabulary, ...level.skills].map((topic) => ({ id: topic.id, type: 'topic' as const, title: topic.title, description: topic.description, href: `/plans/${level.slug}#${topic.id}`, cefrLevels: topic.cefrLevels, tags: topic.tags, access: topic.access, searchTerms: [topic.title, topic.description, ...topic.tags, ...topic.cefrLevels] }))),
  ...textbooks.map((book) => ({ id: book.id, type: 'textbook' as const, title: book.title, description: book.description, href: `/textbooks/${book.slug}`, cefrLevels: book.cefrLevels, tags: [...book.tags, ...book.purpose, book.series, book.publisher], access: book.access, searchTerms: [book.title, book.description, ...book.tags, ...book.purpose, book.series, book.publisher, ...book.authors, ...book.cefrLevels] })),
  ...examGuides.map((exam) => ({ id: exam.id, type: 'exam' as const, title: exam.title, description: exam.description, href: `/exams/${exam.slug}`, cefrLevels: exam.cefrLevels, tags: [...exam.tags, exam.officialName, exam.organization, ...exam.parts], access: exam.access, searchTerms: [exam.title, exam.description, exam.officialName, exam.organization, ...exam.tags, ...exam.parts, ...exam.cefrLevels] })),
  ...resources.map((resource) => ({ id: resource.id, type: 'resource' as const, title: resource.title, description: resource.description, href: `/resources/${resource.slug}`, cefrLevels: resource.cefrLevels, tags: resource.tags, category: resource.category, access: resource.access, searchTerms: [resource.title, resource.description, resource.category, ...resource.tags, ...resource.cefrLevels] })),
];

function score(result: SearchResult, queryTerms: string[]) { return queryTerms.reduce((total, term) => { const title = normalize(result.title); const description = normalize(result.description); const values = result.searchTerms.map(normalize); if (title === term) return total + 100; if (title.includes(term)) return total + 50; if (description.includes(term)) return total + 20; return values.some((value) => value.includes(term)) ? total + 10 : total; }, 0); }
export function searchCatalog(filters: CatalogFilters) { const queryTerms = terms(filters.q); return searchIndex.filter((result) => (!filters.level || result.cefrLevels.includes(filters.level)) && (!filters.type || result.type === filters.type) && (!filters.category || result.category === filters.category) && (filters.free === undefined || (filters.free ? result.access !== 'paid' : result.access !== 'free')) && (!queryTerms.length || queryTerms.every((term) => score(result, [term]) > 0))).map((result) => ({ result, score: score(result, queryTerms) })).sort((a, b) => b.score - a.score || a.result.title.localeCompare(b.result.title, 'ru')).map(({ result }) => result); }
