import { ReviewStatus } from '@/components/content/MaterialDetails';
import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ExternalLink } from '@/components/content/ExternalLink';
import { examGuides } from '@/data';
import { SiteFooter } from '@/components/layout/SiteFooter';
import { SiteHeader } from '@/components/layout/SiteHeader';
type PageProps = { params: Promise<{ exam: string }> };
export const dynamicParams = false;
export function generateStaticParams() { return examGuides.map(({ slug }) => ({ exam: slug })); }
export async function generateMetadata({ params }: PageProps): Promise<Metadata> { const { exam: slug } = await params; const exam = examGuides.find((item) => item.slug === slug); return exam ? { title: `${exam.title}: подготовка`, description: exam.description, alternates: { canonical: `/exams/${exam.slug}` }, openGraph: { title: `${exam.title}: подготовка`, description: exam.description } } : { title: 'Экзамен не найден', robots: { index: false } }; }
export default async function ExamPage({ params }: PageProps) { const { exam: slug } = await params; const exam = examGuides.find((item) => item.slug === slug); if (!exam) notFound(); return <><SiteHeader /><main className="mx-auto max-w-4xl px-4 py-12 sm:px-6"><Link href="/exams" className="text-sm font-medium text-primary hover:underline">← Все экзамены</Link><section className="mt-8 rounded-2xl border bg-muted/30 p-6 sm:p-7"><p className="text-sm font-semibold text-primary">{exam.cefrLevels.join('–')} · {exam.tags[0]}</p><h1 className="mt-2 text-4xl font-bold tracking-tight">{exam.title}</h1><p className="mt-4 max-w-2xl text-lg text-muted-foreground">{exam.description}</p><p className="mt-5 text-sm text-muted-foreground">Организация: {exam.organization}</p><div className="mt-3"><ReviewStatus item={exam} /></div><ExternalLink href={exam.officialUrl} className="mt-6 rounded-md bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground hover:bg-primary/90">Официальный сайт экзамена</ExternalLink></section><section className="mt-12"><h2 className="text-2xl font-bold">Формат</h2><ul className="mt-4 grid gap-3 sm:grid-cols-2">{exam.parts.map((part, index) => <li key={part} className="rounded-lg border p-4 font-medium"><span className="mr-2 text-sm text-muted-foreground">{index + 1}.</span>{part}</li>)}</ul></section><section className="mt-12"><h2 className="text-2xl font-bold">Логика подготовки</h2><ol className="mt-5 space-y-4 border-l pl-6">{exam.preparationStrategy.map((item, index) => <li key={item.phase} className="relative"><span className="absolute -left-[2.05rem] flex h-5 w-5 items-center justify-center rounded-full bg-primary text-xs font-bold text-primary-foreground">{index + 1}</span><h3 className="font-semibold">{item.phase}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{item.focus}</p></li>)}</ol></section><section className="mt-12"><h2 className="text-2xl font-bold">Официальные материалы</h2><ul className="mt-4 space-y-3">{exam.officialMaterials.map((item) => <li key={item.url}><ExternalLink href={item.url} className="font-semibold text-primary hover:underline">{item.title}</ExternalLink></li>)}</ul></section></main><SiteFooter /></>; }
